/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import au.com.dius.pact.consumer.MockServer;
import au.com.dius.pact.consumer.dsl.PactDslJsonBody;
import au.com.dius.pact.consumer.dsl.PactDslWithProvider;
import au.com.dius.pact.consumer.junit.MockServerConfig;
import au.com.dius.pact.consumer.junit5.PactConsumerTestExt;
import au.com.dius.pact.consumer.junit5.PactTestFor;
import au.com.dius.pact.core.model.PactSpecVersion;
import au.com.dius.pact.core.model.RequestResponsePact;
import au.com.dius.pact.core.model.annotations.Pact;
import org.example.model.UserResponse;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;


@ExtendWith(PactConsumerTestExt.class)
@MockServerConfig(hostInterface = "localhost", port = "9292")
@PactTestFor(providerName = "provider_test", pactVersion = PactSpecVersion.V3)
public class UserTest {
    @Pact(consumer = "user-consumer", provider = "user-provider")
    RequestResponsePact pact(PactDslWithProvider builder) {
        return builder
                .uponReceiving("get All user")
                .path("/users")
                .method("GET")
                .matchHeader("authorization", "Bearer Service=([^\\s,]+),customer=([^\\s]+)$", "Bearer Service=eylknsflkks.dummy-service,customer=eynsjkn.dummy=cust")
                .willRespondWith()
                .status(200)
                .body(new PactDslJsonBody()
                        .integerType("id", 1)
                        .stringType("name", "Omkar"))
                .toPact();
    }

    @Test
    @PactTestFor(pactMethod = "pact")
    void test(MockServer server) {

        RestTemplate restTemplate = new RestTemplate();
        String url = server.getUrl()+"/users";
        HttpHeaders headers = new HttpHeaders();
        headers.set("authorization", "Bearer Service=eylknsflkks.dummy-service,customer=eynsjkn.dummy=cust");
        HttpEntity<String> entity = new HttpEntity<>(headers);
        ResponseEntity<UserResponse> response =
                restTemplate.exchange(url, HttpMethod.GET, entity, UserResponse.class);
    }

}
